# docker-compose.yml
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pet_app
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: adopciones_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: